.github/workflows/codeql-analysis.yml, .github/workflows/gradle-verify.yml, .github/workflows/linkcheck.yml, .github/workflows/stale.yml
=> #1 initial github actions for PR build verification

.github/workflows/connector-test.yml, .gitignore, charts/egeria-database-connector-test/Chart.yaml, charts/egeria-database-connector-test/README.md, charts/egeria-database-connector-test/templates/NOTES.txt, charts/egeria-database-connector-test/templates/_helpers.tpl, charts/egeria-database-connector-test/templates/egeria-core.yaml, charts/egeria-database-connector-test/templates/egeria-integration.yaml, charts/egeria-database-connector-test/templates/postgresql.yaml, charts/egeria-database-connector-test/values.yaml
Adds simple k8s action to create a cluster -- no specific containers added yet, just first step
=> #5 setup simple k8s cluster using kind

.github/workflows/connector-test.yml
- waits for test environment containers to be ready
=> #5 wait for test environment to deploy

.github/workflows/connector-test.yml
=> #9 update kind github action

build.gradle, open-metadata-assemblies, postgres-connector/build.gradle, postgres-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/postgres/PostgresDatabaseConnector.java, postgres-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/postgres/PostgresDatabaseProvider.java, postgres-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/postgres/PostgresSourceDatabase.java, postgres-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/postgres/ffdc/PostgresConnectorErrorCode.java, postgres-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/postgres/properties/PostgresColumn.java, postgres-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/postgres/properties/PostgresDatabase.java, postgres-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/postgres/properties/PostgresForeginKeyLinks.java, postgres-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/postgres/properties/PostgresPrimaryKey.java, postgres-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/postgres/properties/PostgresSchema.java, postgres-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/postgres/properties/PostgresTable.java, postgres-connector/src/test/java/org/odpi/openmetadata/adapters/connectors/integration/postgres/properties/PostgresDatabaseTest.java, postgres-connector/src/test/java/org/odpi/openmetadata/adapters/connectors/integration/postgres/properties/PostgresSchemaTest.java
This code drop only runs the "add a new database to egeria" code path, which has been unit tested and is stable with the current test cases. While this code includes the update and delete code it has been disabled and doesn't get executed.
The gradle has been cleaned up , and now only has a single deprecation issue and it builds a "skinny" jar.
The gradle currently copies the connector jar into a directory containing the postgres jdbc jar, and it's this directory is passed to spring, this needs a bit more thought and will be addressed at a later date.
=> DCUT complete of the add database to egeria code path. 

.github/dependabot.yml
=> #17 add dependabot configuration

.github/dependabot.yml
Added dependabot for github actions
=> #17 update path for github actions (requires /)

.github/workflows/connector-test.yml, build.gradle, postgres-connector/build.gradle
Merge in latest dependabot outstanding PRs
=> Merge dependabot updates

build.gradle
=> #47 only apply java-library to subproject

postgres-connector/build.gradle, postgres-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/postgres/PostgresDatabaseConnector.java, postgres-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/postgres/PostgresSourceDatabase.java, postgres-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/postgres/ffdc/PostgresConnectorAuditCode.java, postgres-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/postgres/ffdc/PostgresConnectorErrorCode.java, postgres-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/postgres/mapper/PostgresMapper.java, postgres-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/postgres/properties/PostgresDatabase.java
Fixes: #51
- Gradle dependencies
- spellings & typos
=> Updates following review comments

.github/workflows/gradle-verify.yml, .github/workflows/stale.yml, build.gradle
Merges in dependabot recommended changes & consequential fixes
=> Dependabot 20210526

build.gradle, postgres-connector/build.gradle
=> #16 add maven publishing

gradle/wrapper/gradle-wrapper.properties
=> #16 upgrade to gradle 7

README.md
Fixes: #70
* removes azure link
* removes sonarcloud link
* corrects link to egeria logo
=> #70 Fix status icons in readme

README.md
Fixes: #70
- removes rogue ) in README.md
=> #70 remove rogue )

.dockerignore, .github/workflows/merge.yml, Dockerfile, build.gradle
Fixes: #74 
- Adds Dockerfile for egeria+connector 
- Adds build process for Docker image
- updates version to 2.11-SNAPSHOT
=> Add Dockerfile for postgres connector

Dockerfile
Fixes incorrect addition of postgres connector & jdbc driver
=> #74 fix additional libs needed

Dockerfile
=> #74 fix permissions for postgres driver in docker image

egeria-connector-postgres/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/postgres/mapper/PostgresMapper.java
Signed-off-by: William Bittles <wbittles@uk.ibm.com>
- Fixes column name fix from @wbittles as per  6c67cfa7b887f90496ff40777b701faa49a583b0
- Replaces https://github.com/odpi/egeria-database-connectors/pull/80 (so that readme can be reviewed independently)
=> fix column entity name

.github/workflows/merge.yml, .github/workflows/release.yml, .github/workflows/verify.yml, build.gradle
=> #85 update version to 3.0-SNAPSHOT

build.gradle
=> #85 update version to 2.11

README.md
=> #73 readme updates as per review comments

README.md
Usage notes were just added to main. It makes sense to also have these in the branch for 2.11
=> (Release 2.11) - update release notes 

.github/workflows/merge.yml, Dockerfile
=> #85 correct version in Dockerfile for release

build.gradle, egeria-connector-postgres/build.gradle
Updating gradle build for release testing
=> Update gradle build for release

build.gradle, egeria-connector-postgres/build.gradle
=> Correct quotes for var replace in gradle scripts

egeria-connector-postgres/build.gradle
=> add artifact name to pom

build.gradle, egeria-connector-postgres/build.gradle, gradle/wrapper/gradle-wrapper.properties, settings.gradle
Ports changes made for 2.11 release to main to allow for publishing of future releases of the plugin
=> Update gradle build

build.gradle
=> Update version to 3.1-SNAPSHOT for ongoing development

build.gradle
=> Update version to 3.0 for release

build.gradle
=> Update to release 3.1

build.gradle
=> Update to 3.2-SNAPSHOT

Dockerfile
Fix version of egeria used in Docker image created with connector
=> Fix Docker versions for egeria image;

Dockerfile, build.gradle
Updates development version to 3.3-SNAPSHOT
=> #112 update main to 3.3-SNAPSHOT

Dockerfile, build.gradle
=> #112 update branch to 3.2

Dockerfile, build.gradle
=> Update to final 3.3 release

Dockerfile, build.gradle
=> Update to 3.4-SNAPSHOT release

build.gradle
Updates egeria dependency to 3.4 (from 3.4-SNAPSHOT) in prep for release
=> odpi/egeria#5929 update egeria dependency to 3.4 in prep for release

Dockerfile, build.gradle
Updates version of connector in main to 3.5-SNAPSHOT (ie development)
=> odpi/egeria#5929 update connector version in main to 3.5-SNAPSHOT

Dockerfile
Updates Dockerfile to refer to release 3.4 for the 3.4 branch
=> odpi/egeria#5929 update Dockerfile for 3.4 in release-3.4

.github/workflows/merge.yml
- corrects tag to 3.5-SNAPSHOT
- adds arm64 architecture
=> Correct docker images for main

.github/workflows/merge.yml
- corrects tag to 3.5-SNAPSHOT
- adds arm64 architecture
=> Release 3.4 docker corrections

.github/workflows/connector-test.yml, .github/workflows/merge.yml, Dockerfile, build.gradle
* Updates slf4j-api
* updates postgresql
* Updates setup-helm github action
* Corrects Dockerfile tag version (3.6)
=> Dependencies & Dockerfile tag version

.github/workflows/codeql-analysis.yml, .github/workflows/connector-test.yml, .github/workflows/merge.yml, .github/workflows/release.yml, .github/workflows/stale.yml, .github/workflows/verify.yml, Dockerfile, build.gradle, gradle/wrapper/gradle-wrapper.properties
Merges a number of outstanding PRs relating dependency updates, & moves to egeria 3.9
=> Dependency updates, including egeria 3.9

egeria-resource-connector-jdbc/build.gradle, egeria-resource-connector-jdbc/src/main/java/org/odpi/openmetadata/adapters/connectors/resource/jdbc/JdbcConnector.java, egeria-resource-connector-jdbc/src/main/java/org/odpi/openmetadata/adapters/connectors/resource/jdbc/JdbcConnectorProvider.java, egeria-resource-connector-jdbc/src/main/java/org/odpi/openmetadata/adapters/connectors/resource/jdbc/JdbcMetadata.java, egeria-resource-connector-jdbc/src/main/java/org/odpi/openmetadata/adapters/connectors/resource/jdbc/model/JdbcCatalog.java, egeria-resource-connector-jdbc/src/main/java/org/odpi/openmetadata/adapters/connectors/resource/jdbc/model/JdbcColumn.java, egeria-resource-connector-jdbc/src/main/java/org/odpi/openmetadata/adapters/connectors/resource/jdbc/model/JdbcSchema.java, egeria-resource-connector-jdbc/src/main/java/org/odpi/openmetadata/adapters/connectors/resource/jdbc/model/JdbcTable.java, settings.gradle
Signed-off-by: Liviu Popa <liviu-constantin.popa@ing.com>
=> [egeria-resource-connector] Initial commit

.github/workflows/connector-test.yml, build.gradle, office
Apply outstanding dependant recommendations in single PR
=> Dependabot 20220826

Dockerfile
Updates docker container with current Postgres connector version
=> Update docker container

jdbc-integration-connector/build.gradle, jdbc-resource-connector/build.gradle, jdbc-resource-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/resource/jdbc/JdbcConnector.java, jdbc-resource-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/resource/jdbc/JdbcConnectorProvider.java, settings.gradle
=> Rename resource connector

jdbc-integration-connector/README.MD, jdbc-integration-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/JdbcIntegrationConnector.java
=> Refactored connector type configuration

jdbc-integration-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/transfer/CreateConnectionStructure.java
=> Reverted connection structure creation

jdbc-integration-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/transfer/JdbcMetadataTransfer.java, jdbc-integration-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/transfer/requests/Omas.java, jdbc-integration-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/transfer/requests/OmasGetTables.java
=> Extract tables that belong to no schema

jdbc-integration-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/transfer/DatabaseTransfer.java, jdbc-integration-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/transfer/requests/Jdbc.java, jdbc-integration-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/transfer/requests/JdbcGetCatalogs.java
=> Change database display name and add getCatalogs method

jdbc-integration-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/transfer/ColumnTransfer.java, jdbc-integration-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/transfer/DatabaseTransfer.java, jdbc-integration-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/transfer/JdbcMetadataTransfer.java, jdbc-integration-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/transfer/requests/Jdbc.java, jdbc-integration-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/transfer/requests/JdbcGetColumns.java, jdbc-integration-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/transfer/requests/JdbcGetSchemas.java, jdbc-integration-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/transfer/requests/JdbcGetTables.java
=> Introducing catalog as a jdbc metadata query criteria

jdbc-integration-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/transfer/ColumnTransfer.java, jdbc-integration-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/transfer/requests/Omas.java, jdbc-integration-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/transfer/requests/OmasRemovePrimaryKey.java
=> Added primary key removal

omrs-database-polling-repository-event-mapper/build.gradle
Signed-off-by: David Radley <david_radley@uk.ibm.com>
=> git217 change connector name

omrs-database-polling-repository-event-mapper/build.gradle
Signed-off-by: David Radley <david_radley@uk.ibm.com>
=> git217 remove unused dependancy

jdbc-integration-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/JdbcIntegrationConnector.java
=> Add exclude/include check to make them optional

jdbc-integration-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/transfer/ColumnTransfer.java, jdbc-integration-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/transfer/requests/Omas.java, jdbc-integration-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/transfer/requests/OmasRemoveForeignKey.java
=> Add removal of foreign key relationships

jdbc-integration-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/transfer/JdbcMetadataTransfer.java, jdbc-integration-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/transfer/TableTransfer.java, jdbc-integration-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/transfer/ViewTransfer.java, jdbc-integration-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/transfer/customization/TransferCustomizations.java, jdbc-integration-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/transfer/model/JdbcTable.java, jdbc-integration-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/transfer/requests/Jdbc.java, jdbc-integration-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/transfer/requests/JdbcGetViews.java, jdbc-integration-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/transfer/requests/Omas.java, jdbc-integration-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/transfer/requests/OmasCreateView.java, jdbc-integration-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/transfer/requests/OmasGetTables.java, jdbc-integration-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/transfer/requests/OmasGetViews.java, jdbc-integration-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/transfer/requests/OmasRemoveView.java, jdbc-integration-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/transfer/requests/OmasUpdateSchema.java, jdbc-integration-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/transfer/requests/OmasUpdateView.java
=> Add transferring and filtering of database views
